# Generated by Django 4.1.3 on 2022-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blink", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blink",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
